FROM debian:stable

# Copy the harness-migrate binary into the container
ADD release/linux/amd64/harness-migrate /bin/harness-migrate

# Set the command to run when the container starts
ENTRYPOINT ["/bin/harness-migrate"]
