FROM debian:stable

# Copy the harness-migrate binary into the container
ADD release/linux/amd64/go-fruits-api /bin/go-fruits-api

# Set the command to run when the container starts
ENTRYPOINT ["/bin/go-fruits-api"]
